version: "3.7"
services:
  app:
    build: .
    container_name: fastapi-vk
    ports:
      - "8000:8000"
    environment:
      - ACCESS_TOKEN=your_vk_api_access_token
    volumes:
      - .:/app
    restart: always
